name: flutter_story
repository: https://github.com/shirvanie/flutter_story/tree/master/
issue_tracker: https://github.com/shirvanie/flutter_story/issues
homepage: https://github.com/shirvanie/flutter_story
description: A flutter plugin for creating story (like Instagram, WhatsApp, Telegram, Facebook, etc) for all platforms.
email: ihamedshirvani@gmail.com
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Example of the sliding box on Android.'
    path: flutter_story_demo.webp

flutter:
  uses-material-design: true
